weights: ""
data: "" 
imgsz: 640
conf_thres: 0.2  #0.2
iou_thres: 0.45 #0.45
max_det: 10
device: '0'  # cuda device, i.e. 0 or 0,1,2,3 or cpu
view_img: False  # show results
draw_img: False
save_img: False
classes: None # [0] #["0","1","2","3","4","5","6","7","8"]
agnostic_nms: True  # class-agnostic NMS
multi_label: False
augment: False  # augmented inference
#visualize: False  # visualize features
line_thickness: 3  # bounding box thickness (pixels)
half: False  # use FP16 half-precision inference
dnn: False  # use OpenCV DNN for ONNX inference
